//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheProfessionalStalker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class objecten
    {
        public string naam { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public string plaats { get; set; }
        public string beschrijving { get; set; }
        public string persoon { get; set; }
        public string postcode { get; set; }
    }
}
