//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheProfessionalStalker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class persoon
    {
        public int id { get; set; }
        public string voornaam { get; set; }
        public string achternaam { get; set; }
        public string tussenvoegsel { get; set; }
        public string geslacht { get; set; }
        public string plaats { get; set; }
        public string straat { get; set; }
        public Nullable<int> huisnummer { get; set; }
        public string postcode { get; set; }
        public string land { get; set; }
        public Nullable<System.DateTime> startdatum { get; set; }
        public Nullable<System.DateTime> einddatum { get; set; }
        public string relatie { get; set; }
    
        public virtual relatie relatie1 { get; set; }
    }
}
